//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.16 at 12:30:48 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.eti.pg.gda.pl/kask/javaee/wieze", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.gda.pg.eti.kask.javaee.wieze;
